name: Bug report
description: Отчёт о дефекте
title: "[Ошибка]: "
labels: ["bug"]
body:
  - type: textarea
    id: Description
    attributes:
      label: Описание
    validations:
      required: true
