name: Bug report
description: Отчёт о дефекте
title: "[Ошибка]: "
labels: ["bug"]
body:
  - type: textarea
    id: 1
    attributes:
      label: Описание
    validations:
      required: true
      
  - type: textarea
    id: 2
    attributes:
      label: Шаги воспроизведения
    validations:
      required: true

  - type: textarea
    id: 3
    attributes:
      label: Ожидаемый результат
    validations:
      required: true

  - type: textarea
    id: 4
    attributes:
      label: Фактический результат
    validations:
      required: true

  - type: textarea
    id: 5
    attributes:
      label: Скриншоты / Доп. материалы
      
  - type: textarea
    id: 5
    attributes:
      label: Среда выполнения
      placeholder: Операционная система, IDE и прочие программные особенности необходимые для нахождения дефекта

  - type: dropdown
    id: 6
    attributes:
      label: Приоритет
      options:
       - Высокий
       - Средний
       - Низкий
    validations:
      required: true

  - type: dropdown
    id: 7
    attributes:
      label: Серьёзность
      options:
       - Критическая
       - Высокая
       - Средняя
       - Низкая
    validations:
      required: true
