name: Bug report
description: Отчёт о дефекте
title: "[Ошибка]: "
labels: ["bug"]
body:
  - type: textarea
    id: Description
    attributes:
      label: Описание
    validations:
      required: true
      
  - type: textarea
    id: Playback_steps
    attributes:
      label: Шаги воспроизведения
    validations:
      required: true

  - type: textarea
    id: Expected_result
    attributes:
      label: Ожидаемый результат
    validations:
      required: true

  - type: textarea
    id: Actual_result
    attributes:
      label: Фактический результат
    validations:
      required: true
